### ISSUE TITLE
Протестировать новый сервер

### ISSUE THREAD

**Issue by johnlife** [johnlife/Glimpse-Android#68]
Версия клиента, настроенного на временный дев-сервер в дропбоксе: https://www.dropbox.com/s/ga9sxxzh0zfqxuy/Glimpse_new_server.apk?dl=0

Сервер: http://frame.uzere.name:1337/
логин admin, пароль bih7drptby

рамки добавляются/удаляются, ящики получают в @testmx.uzere.name, в поле и userdata.txt только имя, то что до @

То есть: 
1. заходим в админку на сервере, создаем юзера с действующим ящиком (можно использовать 10minutemail.com) (main email)
2. создаем адрес рамки *some_thing*
3. на девайсе в userdata.txt прописываем тот же *some_thing*
4. шлем фотку с любого ящика на *some_thing*@testmx.uzere.name
5. первый раз должно прийти письмо на main email c просьбой подтвердить/заблокировать мыло, с которого пришла фотка.
6. идем по ссылке в письме и блокируем/разрешаем этот мыл
7. проверяем что мыл попал в черный/белый список
8. если мыл разрешили - должна прийти первая картинка
9. проверяем что дальнейшие письма с этого мыла игнорируются / проходят сразу

**Comment by johnlife** [comment]
Важно - если белый список пуст - списочная система не работает. То есть в белый список внести вручную хотя-бы один адрес

**Comment by Woffkaa** [comment]
После нажатия Approve/Deny
Error: Invalid token
   at Query.<anonymous> (/home/uzere/skylight/src/routes/index.js:51:34)
   at /home/uzere/skylight/node_modules/mongoose/node_modules/kareem/index.js:177:19
   at /home/uzere/skylight/node_modules/mongoose/node_modules/kareem/index.js:109:16
   at doNTCallback0 (node.js:407:9)
   at process._tickCallback (node.js:336:13)

**Comment by johnlife** [comment]
На текущий момент фотографии на рамку с пустыми списками не приходят.

**Comment by johnlife** [comment]
На текущий момент с этой системой все очень плохо на стороне клиента - очень ругается. Сегодня надо постараться максимально сломать систему и понять почему у нас работает а у него - нет.

**Comment by johnlife** [comment]
[9:22:35 AM] UTC+7
i just tried adding an entirely new account, and a new Skylight address to that account.
in the case where there is no whitelist, email did not go through. in the case where there is a whitelist and email is on the whitelist, it did not go through.
this account is mysegal@verizon.net/ marksegal@testmx.uzere.name
so yeah, basically nothing working. yesterday, so photos got through, but today can’t get anything to go through.

[9:27:57 AM] 
btw i also tried the email test on two wifi networks and that didn’t help. so it’s definitely either the email server, the front end code interacting with the email server, or the whitelist system.
seeing whether the emails are getting queued  or whether the server is getting pinged by the frame will be useful.
